Workaround overflow errors with Numpy ≥ 2.
This change works around OverflowError regressions caught by the test
suite with Numpy 2 and later, independently reported in [issue #127]
and in [Debian bug #1095090], by restoring the former (potentially
buggy) behavior with uncaught overflows.  Issues manifested like:

	  File "/home/shuaiw/miniconda3/envs/methy/lib/python3.12/site-packages/pbcore/io/align/_BamSupport.py", line 66, in rgAsInt
	    return np.int32(int(rgIdString.split("/")[0], 16))
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	OverflowError: Python integer 3367457666 out of bounds for int32

and like:

	    def _gapify(self, data, orientation, gapOp):
	        if self.isUnmapped:
	            return data

	        # Precondition: data must already be *in* the specified orientation
	        if data.dtype == np.int8:
	            gapCode = ord("-")
	        else:
	>           gapCode = data.dtype.type(-1)
	E           OverflowError: Python integer -1 out of bounds for uint8

While being at it, the change includes a fix proposal for situations
where identifiers include hyphenations, fixing:

	    return np.int32(int(rgIdString.split("/")[0], 16))
	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 16: 'cb4d472d-100C60F6'

[issue #127]: https://github.com/PacificBiosciences/pbcore/issues/127
[Debian bug #1095090]: https://bugs.debian.org/1095090

Signed-Off-By: Étienne Mollier <emollier@debian.org>